/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ServiceCard from "./ServiceCard";

const servicesData = [
  {
    icon: "/servicesection/service1.svg",
    title: "Company Registration",
    description: '"Navigate the legal landscape with ease."',
  },
  {
    icon: "/servicesection/service2.svg",
    title: "Fundraising",
    description: '"Secure the capital you need to grow."',
  },
  {
    icon: "/servicesection/service3.svg",
    title: "Growth Strategy",
    description: '"Develop strategies to scale your business."',
  },
  {
    icon: "/servicesection/service4.svg",
    title: "Efficiency Optimization",
    description: '"Maximize your operational efficiency."',
  },
  {
    icon: "/servicesection/service5.svg",
    title: "End-to-End Support",
    description:
      '"Providing solutions at every stage of your startup journey."',
  },
];

const Services: React.FC = () => {
  return (
    <div className="flex overflow-hidden flex-col items-center w-full bg-white min-h-[653px] max-md:px-5 max-md:max-w-full">
      <div className="flex flex-col w-full max-w-[1320px] max-md:max-w-full">
        <div className="flex flex-wrap justify-center w-full max-md:max-w-full">
          {servicesData.map((service, index) => (
            <ServiceCard ImageSrc={""} ImageAlt={""} key={index} {...service} />
          ))}
        </div>
      </div>
    </div>
  );
};

export default Services;
7