/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ServiceCard from "./ServiceCard";

const servicesData = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/438953360af13d473d12d182f1e89eb92c8c5501adb89b7188b39f883c479bcb?placeholderIfAbsent=true&apiKey=bc78d96b1bfe4229ab8bdab79a935f37",
    title: "Company Registration",
    description: '"Navigate the legal landscape with ease."',
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/2e31baa8aa002b01802523c568133f9b45de6b4fdad77dbc13b4049de6acac99?placeholderIfAbsent=true&apiKey=bc78d96b1bfe4229ab8bdab79a935f37",
    title: "Fundraising",
    description: '"Secure the capital you need to grow."',
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/7fad58727f66f7c54be4fb458465555e6bb2f2e6d20f3e36faa2133001102cc2?placeholderIfAbsent=true&apiKey=bc78d96b1bfe4229ab8bdab79a935f37",
    title: "Growth Strategy",
    description: '"Develop strategies to scale your business."',
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/b95a34902fa8fae2f6ff9fbd4ffd50730eccf2522f0457beff2bffe6f538f611?placeholderIfAbsent=true&apiKey=bc78d96b1bfe4229ab8bdab79a935f37",
    title: "Efficiency Optimization",
    description: '"Maximize your operational efficiency."',
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/e967612e83be2fd98830d3a1f59c2fc2d3faed40f5f034c81c218b447d23ad2e?placeholderIfAbsent=true&apiKey=bc78d96b1bfe4229ab8bdab79a935f37",
    title: "End-to-End Support",
    description:
      '"Providing solutions at every stage of your startup journey."',
  },
];

const Services: React.FC = () => {
  return (
    <div className="flex overflow-hidden flex-col items-center w-full bg-white min-h-[653px] max-md:px-5 max-md:max-w-full">
      <div className="flex flex-col w-full max-w-[1320px] max-md:max-w-full">
        <div className="flex flex-wrap justify-center w-full max-md:max-w-full">
          {servicesData.map((service, index) => (
            <ServiceCard key={index} {...service} />
          ))}
        </div>
      </div>
    </div>
  );
};

export default Services;
